### ISSUE TITLE
Please help a n00b!

### ISSUE THREAD

**Issue by runnerpack** [zserge/fenster#12]
**Thanks for making fenster!**

I'm attempting to use MSYS2 to build the examples in Windows 7.
I can get the code in examples/drawing-c to compile, but when I run the resulting executable, I only get an empty console window and another window that only contains black pixels.
GCC gave some warnings related to the initialization of a BITMAPINFO header, which I was able to eliminate – although possibly incorrectly – but the outcome is the same.
I've gotten this result on two different systems. On the second, MSYS2 was freshly installed.
I realize that Windows 7 is old, and Windows support in general is probably an afterthought, but I love the concept of fenster, and I would _really_ like to use it to make truly cross-platform applications.
**Thanks!**

**Comment by teovilo** [comment]
I'm on Windows running TDM-GCC 32bit and have the same issue. I've ignored the warnings for now. Window is blank and looks to be loading something when I put my cursor over it.

I'm wondering if the issue has something to do with the OS time call? The window does not close after 60s.

**Comment by runnerpack** [comment]
I don't see the "wait" cursor on mine, so that's a little different. What Windows version are you running?
Also, I don't think the "60" means 60 seconds. I think it's dividing 1000 by 60 to get 60 frames per second (1000 milliseconds in a second) and that's how often the window is updated.
It works fine on my Ubuntu derivative (I'm trying ElementaryOS, even though I'm not a Mac user).  There is a small issue with the bottom few lines of the framebuffer having random junk pixels, which I have worked around until I can look into the cause, and the Doom port doesn't have sound, unlike the separate sound example, but everything else seems fine.
I feel this is getting quite a bit off-topic… 😅

**Comment by recidivism5** [comment]
The BITMAPINFO problem is caused by fenster.h attempting to access 2 nonexistent array elements of type RGBQUAD from a BITMAPINFO struct. I have submitted a pull request that fixes this issue by using a custom struct that has the necessary 3 RGBQUADs.

**Comment by vaguinerg** [comment]
Please close
