### ISSUE TITLE
The example crashes

### ISSUE THREAD

**Issue by milen-prg** [zserge/fenster#27]
The example crashes (when the exe file is started), the ) if increase the windows size:

`#include "fenster.h"
#define W 600
#define H 800
int main() {
  uint32_t buf[W * H];
  struct fenster f = { .title = "hello", .width = W, .height = H, .buf = buf };
  fenster_open(&f);
  while (fenster_loop(&f) == 0) {
    for (int i = 0; i < W; i++) {
      for (int j = 0; j < H; j++) {
        fenster_pixel(&f, i, j) = rand();
      }
    }
  }
  fenster_close(&f);
  return 0;
}`

Windows 10 Pro 64 bit, Visual Studio 2022. All last updated.
![image](https://github.com/zserge/fenster/assets/59639866/dd0c5718-2171-4e8d-8671-7568feca793c)

**Comment by dartvader316** [comment]
`1920000 (4 * 600 * 800)` is pretty big for stack array. 
You can try to allocate `buf` on heap:
```
uint32_t* buf = calloc(W*H, sizeof(uint32_t));
```
You will also have to free it at the program end to prevent memory leak.

**Comment by milen-prg** [comment]
@dartvader316 this must not be. The array in stack with this size must not be any problem, I have 64GB RAM. What is the point of using the heap, when the example suggests normal array in stack memory?

**Comment by dartvader316** [comment]
>  The array in stack with this size must not be any problem, I have 64GB RAM

Stack is limited to 1MB by default with most compilers/OSes. You can increase it with compiler parameters or with increasing OS limits but stack still was not meant to be used for such big allocations. For big buffer allocations on any usual user OS you need to use heap.
