### ISSUE TITLE
Is uint32_t color alpha ignored?

### ISSUE THREAD

**Issue by gamecubate** [zserge/fenster#30]
Hi.

In `fenster.h`, `kCGImageAlphaNoneSkipFirst` would hint at the fact that fenster does not support transparency (8 bit alpha; msb of uint32_t color value). Is this correct?

EDIT: I am asking because overlaying rects with partial transparency, say 0x88FF0000, draws each rect at full opacity. And if so, bummer because everything else about this lib is perfect for my needs.

**Comment by vaguinerg** [comment]
The README states RGB support, not RGBA.
